In [189]:
def compress(uncompressed = 'bananabandan'):
    ## step 1: initial dictionary
    init_dic = {'a': 'a',
                'b': 'b',
                'd': 'd',
                'n': 'n'}

    ## step 2: compressing and updating dictionary
    dictionary = init_dic
    previous_str = ""
    compressed_result = []
    for current_char in uncompressed:
        pre_cur = previous_str + current_char

        if pre_cur in dictionary:
            previous_str = pre_cur
        else:
            ## step 2.1: getting compressed code for previous str
            previous_str_code = dictionary[previous_str]
            compressed_result.append(previous_str_code)

            ## step 2.2: updating the dictionary.
            dictionary[pre_cur] = len(dictionary)
            previous_str = current_char

    ## getting compressed code for the last previous str
    compressed_result.append(dictionary[previous_str])

    print(dictionary)
    return compressed_result


def decompress(compressed):
    ## init dictionary
    init_dic = {'a': 'a',
                'b': 'b',
                'd': 'd',
                'n': 'n'}

    dictionary = init_dic
    prev_code = decompress_result = compressed.pop(0)
    for curr_code in compressed:

        ## decompressed
        if curr_code in dictionary:
            curr_code_decomp = dictionary[curr_code]
        elif curr_code == len(init_dic):
            curr_code_decomp = prev_code + prev_code[0]
        else:
            raise ValueError('Bad compressed code: %s' % curr_code)
        decompress_result += curr_code_decomp

        ## updating dictionary
        dictionary[len(dictionary)] = prev_code + curr_code_decomp[0]
        prev_code = curr_code_decomp

    print(dictionary)
    return decompress_result

In [190]:
# bananabandan
compress()

{'a': 'a', 'b': 'b', 'd': 'd', 'n': 'n', 'ba': 4, 'an': 5, 'na': 6, 'ana': 7, 'ab': 8, 'ban': 9, 'nd': 10, 'da': 11}


['b', 'a', 'n', 5, 'a', 4, 'n', 'd', 5]

In [4]:
import numpy as np

b = np.array(a)

In [192]:
(1.5**2+2.5**2+3.5**2)/(0.5**2+0.5**2+0.5**2)

27.666666666666668

In [50]:
a = [0, 1, 2, 3, 4, 99, 100]
b = [100, 11, 123, 145, 1, 9, 10]

In [51]:
a = np.asarray(a)
b = np.asarray(b)

In [52]:
a/b

array([ 0.        ,  0.09090909,  0.01626016,  0.02068966,  4.        ,
       11.        , 10.        ])

In [23]:
c = [[[1,2], [3,4], [5, 6]]]
c = np.asarray(c)
for i in c:
    print(i)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
d = np.asarray(c)

In [25]:
d.shape

(1, 3, 2)

In [1]:
import numpy as np
a = np.zeros((2, 3))
b = np.array([0, 99])


In [153]:
a[b > 0.5, 0] = 1
a

array([[-0.70089287, -0.02873069],
       [ 1.        , -0.15671971],
       [ 0.02213162, -1.43482794]])

In [186]:
a = [[0, 1, 0, 0, 0], [1, 1, 1, 1, 1]]

In [188]:
a[0].index(1)

1

In [183]:
b = np.where(a==1)
b

(array([0, 1, 1, 1, 1, 1]), array([1, 0, 1, 2, 3, 4]))

In [103]:
import librosa

n = np.random.rand(64, 40, 3200)

In [104]:
stds = np.std(n, axis=2)

In [106]:
mean = np.mean(stds, axis=1).reshape(64, 1)
min = np.min(stds, axis=1).reshape(64, 1)


In [107]:
t = (stds - mean) / (mean - min)
t.shape

(64, 40)

In [110]:
vars = t**2
vars.shape

(64, 40)

In [148]:
preds = np.zeros((64, 40, 4))

In [149]:
preds[vars < 0.5, 0] = 1

In [151]:
preds.shape

(64, 40, 4)

In [150]:
np.count_nonzero(preds)

2189

In [135]:
rms = np.sqrt(np.sum(noise**2, axis=1)/3200)

In [136]:
rms.shape

(2189,)

In [146]:
a2 = np.array([rms, rms])

In [147]:
a2.shape

(2, 2189)