In [ ]:
def compress(uncompressed = 'bananabandan'):
    ## step 1: initial dictionary
    init_dic = {'a': 'a',
                'b': 'b',
                'd': 'd',
                'n': 'n'}

    ## step 2: compressing and updating dictionary
    dictionary = init_dic
    previous_str = ""
    compressed_result = []
    for current_char in uncompressed:
        pre_cur = previous_str + current_char

        if pre_cur in dictionary:
            previous_str = pre_cur
        else:
            ## step 2.1: getting compressed code for previous str
            previous_str_code = dictionary[previous_str]
            compressed_result.append(previous_str_code)

            ## step 2.2: updating the dictionary.
            dictionary[pre_cur] = len(dictionary)
            previous_str = current_char

    ## getting compressed code for the last previous str
    compressed_result.append(dictionary[previous_str])

    print(dictionary)
    return compressed_result


def decompress(compressed):
    ## init dictionary
    init_dic = {'a': 'a',
                'b': 'b',
                'd': 'd',
                'n': 'n'}

    dictionary = init_dic
    prev_code = decompress_result = compressed.pop(0)
    for curr_code in compressed:

        ## decompressed
        if curr_code in dictionary:
            curr_code_decomp = dictionary[curr_code]
        elif curr_code == len(init_dic):
            curr_code_decomp = prev_code + prev_code[0]
        else:
            raise ValueError('Bad compressed code: %s' % curr_code)
        decompress_result += curr_code_decomp

        ## updating dictionary
        dictionary[len(dictionary)] = prev_code + curr_code_decomp[0]
        prev_code = curr_code_decomp

    print(dictionary)
    return decompress_result

In [ ]:
# bananabandan
compress()

In [1]:
import numpy as np
import pandas as pd
import os
import librosa

targets = np.zeros((50, 9), dtype=float)

In [2]:
ensemble_dir = './datasets/ensemble_data/data.csv'


In [5]:
file = pd.read_csv(ensemble_dir, header=None, sep='\t')

In [35]:
a = file.to_numpy()

In [88]:
target = a[0][~np.isnan(a[0])]
target = np.hsplit(target, len(target)/3)
target

[array([0.   , 0.816, 2.672]), array([2.   , 5.6  , 9.546])]

In [92]:
(32+3*8*2+2*16)/64

1.75

In [91]:
temp = []
temp.append(target)
np.asarray(temp).shape

(1, 2, 3)

In [42]:
data_dir = './datasets/data'
output_dir = './datasets/data/ensemble'
labels = ['snoring', 'cough', 'move']

snoring_path = os.path.join(data_dir, labels[0])
cough_path = os.path.join(data_dir, labels[1])
move_path = os.path.join(data_dir, labels[2])

In [179]:
test_audio = librosa.load('./01.wav', sr=32000, mono=True)

In [178]:
test_audio = np.random.normal(0, 1, 32000)

In [197]:
# Generate white noise
noise = np.random.normal(0, 1, 32000)

# Normalize the white noise
noise = noise / np.max(np.abs(noise))

# Convert the white noise to a 16-bit format
# noise = (noise * 2**15).astype(np.int16)

In [198]:
np.sum(noise)

34.77931565197062

In [195]:
def get_rlh(frame, alpha=0.25):
        frame_length = len(frame)
        low_band, high_band = alpha * frame[0], alpha * frame[0]
        rms_low, rms_high = low_band**2, high_band**2

        for i in range(1, len(frame)):
            # low_band[i] = low_band[i-1] + self.alpha*(frame[i] - frame[i-1])
            # high_band[i] = self.alpha*(high_band[i-1] + frame[i] - frame[i-1])
            low_band += alpha*(frame[i] - frame[i-1])
            high_band = alpha*(high_band + frame[i] - frame[i-1])
            rms_low += low_band**2
            rms_high += high_band**2

        rms_low = np.sqrt(rms_low/frame_length)
        rms_high = np.sqrt(rms_high/frame_length)
        
        return rms_low / rms_high if rms_high != 0 else 0

In [199]:
get_rlh(noise)

0.7920238319050019

In [97]:
np.argmax(a, axis=2).shape

(32, 40)

In [92]:
def foo(i):
    return len(i)

In [109]:
a = [1,2,3]
b = [4,5,6]
c=[7,8,9]

d = np.array([a,b,c])

In [113]:
e=d.transpose(-1,0)

In [115]:
e.transpose(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [116]:
from sklearn.datasets import load_iris

iris = load_iris()

x, y = iris.data, iris.target

In [162]:
x = np.random.rand(12,3,3)

In [161]:
y = np.random.rand(12,3)

In [163]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(x, y)

ValueError: Found array with dim 3. DecisionTreeClassifier expected <= 2.

In [128]:
clf.predict([[1,2,3,0], [0,0,0,0],[-1,-1,-1,-1]])

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])

In [145]:
a = np.array([1,2,3,4])
b = np.zeros((4, 5))

In [146]:
b[a] = 1

IndexError: index 4 is out of bounds for axis 0 with size 4

In [143]:
b

array([[0., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.]])

In [148]:
predicted_labels[0]

1

In [149]:
predicted_probabilities[0]

array([0.00378527, 0.82720471, 0.16901001])

In [169]:
a = np.random.rand(9,3)

In [168]:
b = np.array([1,2,3,0,5,6,7,0,0])

In [170]:
clf.fit(a, b)

DecisionTreeClassifier()

In [200]:
1/1e10

1e-10

In [202]:
np.sqrt(1e-100)

1e-50

In [204]:
1e-500/1e-50

0.0